# Generated by Django 4.2.13 on 2024-07-09 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_customer_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('default_customer_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('default_customer_city', models.CharField(blank=True, max_length=40, null=True)),
                ('default_customer_county', models.CharField(blank=True, max_length=80, null=True)),
                ('default_customer_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('default_customer_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('default_customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
