# Generated by Django 4.2.13 on 2024-07-06 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_merchitem'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_address1', models.CharField(max_length=80)),
                ('customer_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('customer_city', models.CharField(max_length=40)),
                ('customer_county', models.CharField(blank=True, max_length=80, null=True)),
                ('customer_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_country', models.CharField(max_length=40)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MerchLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merch_item_size', models.CharField(blank=True, max_length=2, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('merch_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.merchitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merch_line_items', to='checkout.order')),
            ],
        ),
        migrations.CreateModel(
            name='BeerLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.beer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_line_items', to='checkout.order')),
            ],
        ),
    ]
