# Generated by Django 4.2.13 on 2024-07-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('checkout', '0004_alter_order_customer_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='profiles.customerprofile'),
        ),
    ]
