# Generated by Django 4.2.13 on 2024-07-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_merchitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='merchitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
